#:import MapView kivy_garden.mapview.MapView
#:import GpsBlinker gpsblinker.GpsBlinker
#:include gpsblinker.kv

<HomeMapView>:
    lat: 48.8588897
    lon: 2.320041
    zoom: 10
    #on_zoom:
    #    self.zoom = 5 if self.zoom < 5 else self.zoom
    double_tap_zoom: True
    on_lat:
        self.start_getting_markets_in_fov()
    on_lon:
        self.start_getting_markets_in_fov()
    GpsBlinker:
        lat: root.lat
        lon: root.lon
        id: blinker

