name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " event ${{ github.event_name }}/ "
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: installing dependencies
        run : python -m pip install -r requirements.txt
      - name: Linting Code
        run : pylint src/main/