name: Deploy
on: [push]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: installing dependencies
        run : python -m pip install -r requirements.txt
      - name : Format Code
        run : black src/
      - name: Lint Code
        run : pylint src/
#      - name: Test Code
#        run : pytest src/test/data/test.py ; \
#              pytest src/test/web_app/test.py
