name: Deploy
on: [push]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: installing dependencies
        run : python -m pip install -r requirements.txt
      - name : Format Code
        run : black src/
      - name: Lint Code
        run : pylint src/
  replace-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Replace tokens
        run : echo ${{ secrets }}
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.json"]'
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
          RDS_CONF_PWD: ${{ secrets.RDS_CONF_PWD }}

#      - name: Test Code
#        run : pytest src/test/data/test.py ; \
#              pytest src/test/web_app/test.py
